ENABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  - SPELL_VALE
  - REPOSITORY_LYCHEE

MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.jsonc
SPELL_VALE_CONFIG_FILE: .vale.ini

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
